### ISSUE TITLE
mentor update profile not working

### ISSUE THREAD

**Issue by aniarya82** [icyflame/mentorship-website-cum-portal#25]

**Comment by icyflame** [comment]
Have you tested this on mentorship website or on local host?

**Comment by aniarya82** [comment]
Yup, on both localhost and online, the update thing is not working with mentor profile

**Comment by icyflame** [comment]
Okay. Thanks for the update. I will look into it.

**Comment by icyflame** [comment]
Debugged. This is the log output for the update function:

``` shell
Completed 500 Internal Server Error in 5ms

ActiveRecord::UnknownAttributeError (unknown attribute: current_password):
  app/controllers/mentors/registrations_controller.rb:11:in `update_resource'
```

**Comment by icyflame** [comment]
# Problem Identified.

The update function has been activated without the current password. And thus, we can remove that from the edit profile window.

Devise defaults require it to be there, but I have changed it, so that the profile can be updated without the current password.

**Comment by aniarya82** [comment]
peace

**Comment by icyflame** [comment]
Fixed this issue in https://github.com/light94/mentorship-portal/commit/d75388c221b950058a4bb5d411d46a0829436273.

@aniarya82 : Nice work!
