### ISSUE TITLE
Create a partial profile page of the mentor to be shown to the mentee

### ISSUE THREAD

**Issue by icyflame** [icyflame/mentorship-website-cum-portal#35]

**Comment by icyflame** [comment]
@aniarya82 
The profile page of the mentor that is shown to the student should only have his company, designation and his email ID, his social networking links. **Ensure that the student doesn't have access to the phone number.** We may release this information, if required, at a later stage.
Can you work on this?

**Comment by aniarya82** [comment]
where will the mentee see this page

**Comment by icyflame** [comment]
he will see it once the mentor has been allotted to him. We can say that 

```
A mentor has been allotted to you. View his profile.
```

And add a link. This will allow him to know more about his/her mentor.

**Comment by aniarya82** [comment]
so this View his profile link would open a new page right

**Comment by icyflame** [comment]
It depends on you. You may use any one of the following:
- Modals (bootstrap)
- [Lity](https://github.com/jsor/lity) (lightboxes)
- [SweetAlert](https://github.com/t4t5/sweetalert)

It's basically a design thing, so, whatever you think is good, you can use that! New page is also fine! :smile: 

And, before you start working, just post here what you have selected as the interface.

**Comment by icyflame** [comment]
Solved by @aniarya82 

Refer: https://github.com/light94/mentorship-portal/pull/26
