### ISSUE TITLE
Make both the student and the mentor models timeoutable

### ISSUE THREAD

**Issue by icyflame** [icyflame/mentorship-website-cum-portal#4]

**Comment by icyflame** [comment]
@light94 What do you think?

Timeoutable will timeout the login of a student/mentor after the defined time.

**Comment by mrahul17** [comment]
This feature is definitely good, but I think it is an overkill for our purpose. For the time being let's drop this idea and later on, when the rush is over, we can implement it.

**Comment by icyflame** [comment]
It can be implemented very easily. (It is just adding one more line. )

What I meant when I said whether we need it was that, if the user was logged out of the portal, he/she may feel reluctant to log back in. 

So, we are talking about the need of this feature from a UX point of view.

**Comment by mrahul17** [comment]
That's what overkill would mean in this context. This feature is implemented in only very secure websites or high traffic websites, basically whenever it is expected that the server might fail with too many concurrent connections.
If you understand this,you would agree that this is not needed right now.

**Comment by icyflame** [comment]
Yes. Indeed. We don't really need it for now and may never need it.
